# Valid Login
valid.username=
valid.password=

# Invalid Login
invalid.username=
invalid.password=

empty.username=
empty.password=

# Error Messages
error.empty.username=
error.empty.password=
error.invalid.credentials=
